SpawnEntityFromTable("info_particle_system",
{
	angles = "0 0 0",
	origin = "-1841 2153 -312",
	effect_name = "unusual_souls_green_rising",
	flag_as_weather = "0",
	start_active = "0",
	targetname = "halloween.garg01particles"
});

SpawnEntityFromTable("prop_dynamic",
{
	angles = "0 139 0",
	DisableBoneFollowers = "0",
	disablereceiveshadows = "1",
	disableshadows = "1",
	ExplodeDamage = "0",
	ExplodeRadius = "0",
	fademaxdist = "900",
	fademindist = "900",
	fadescale = "0",
	MaxAnimTime = "10",
	maxdxlevel = "0",
	MinAnimTime = "5",
	mindxlevel = "0",
	model = "models/props_halloween/gargoyle_backpack.mdl",
	modelscale = "1.0",
	PerformanceMode = "0",
	pressuredelay = "0",
	RandomAnimation = "0",
	renderamt = "255",
	rendercolor = "255 255 255",
	renderfx = "0",
	rendermode = "0",
	SetBodyGroup = "0",
	skin = "0",
	solid = "6",
	spawnflags = "0",
	StartDisabled = "0",
	targetname ="halloween.garg01",
	origin = "-1841 2153 -342"
});

SpawnEntityFromTable("prop_dynamic",
{
	angles = "0 191 0",
	DisableBoneFollowers = "0",
	disablereceiveshadows = "1",
	disableshadows = "1",
	ExplodeDamage = "0",
	ExplodeRadius = "0",
	fademaxdist = "1200",
	fademindist = "1300",
	fadescale = "1",
	MaxAnimTime = "10",
	maxdxlevel = "0",
	MinAnimTime = "5",
	mindxlevel = "0",
	model = "models/props_halloween/jackolantern_01.mdl",
	modelscale = ".85",
	PerformanceMode = "0",
	pressuredelay = "0",
	RandomAnimation = "0",
	renderamt = "255",
	rendercolor = "255 255 255",
	renderfx = "0",
	rendermode = "0",
	SetBodyGroup = "0",
	skin = "0",
	solid = "6",
	spawnflags = "0",
	StartDisabled = "0",
	targetname = "halloween.jack01",
	origin = "-3984 1432 -466"
});

SpawnEntityFromTable("prop_dynamic",
{
	angles = "0 1.50001 0",
	DisableBoneFollowers = "0",
	disablereceiveshadows = "1",
	disableshadows = "1",
	ExplodeDamage = "0",
	ExplodeRadius = "0",
	fademaxdist = "1400",
	fademindist = "1300",
	fadescale = "1",
	MaxAnimTime = "10",
	maxdxlevel = "0",
	MinAnimTime = "5",
	mindxlevel = "0",
	model = "models/props_halloween/jackolantern_02.mdl",
	modelscale = "1",
	PerformanceMode = "0",
	pressuredelay = "0",
	RandomAnimation = "0",
	renderamt = "255",
	rendercolor = "255 255 255",
	renderfx = "0",
	rendermode = "0",
	SetBodyGroup = "0",
	skin = "0",
	solid = "6",
	spawnflags = "0",
	StartDisabled = "0",
	targetname = "halloween.jack02",
	origin = "75 3779 -421"
});